### ISSUE TITLE
Won't do anything?

### ISSUE THREAD

**Issue by dovy** [joshhunt/tvos-iview#1]
I love the concept, but I try to run it and nothing happens...

**Comment by joshhunt** [comment]
Did you make sure you're running the dev build server?

```
cd client
npm install
npm start
```

By default, the app will load the TVJS package from `http://localhost:8123/bundle.js`. You might need to update that in AppDelegate.swift if you're running in on a physical Apple TV.

Also, this project uses API's from an Australia catchup TV video-on-demand service, which may or may not be geoblocked. Make sure you can access `https://iview.abc.net.au/api/home?device=hbb&appVer=apple-tv-dev`.
