### ISSUE TITLE
Socket IO error when run the xcodeproj

### ISSUE THREAD

**Issue by thibautdelille** [joshhunt/tvos-iview#2]
Hello Josh,

Nice work here, I was trying to make the live reload work but keep hitting the same issue. When I run the app, it return the following error:

```
2016-08-08 10:13:59.842 tvos-au-vod[9254:239726] ITML <Error>: TypeError: undefined is not an object (evaluating 'Object.prototype')...{
    column = 30;
    line = 10998;
    sourceURL = "http://localhost:8123/bundle.js";
}
```

If I comment out the Socket.io implementation [here](https://github.com/joshhunt/tvos-au-vod/blob/master/client/src/lib/liveReload.js#L3) the app run well but of course socket.io doesn't.

Am I missing something here?

**Comment by joshhunt** [comment]
Hmmm - it _should_ just work. What version of tvOS/SDK are you running this
on?

To get socket.io working in the TVJS environment we have to stub out a
whole bunch of stuff. I suspect that In an update to socket.io is using
something 'new' that I haven't stubbed.

I'll check it out later when I get a chance. In the meantime you could try
installing the exact version of socket.io that's in the package.json file
(remove the ^caret)

**Comment by thibautdelille** [comment]
Thanks, forcing socket.io to 1.3.7 works. I'll investigate If I can add a stub for those new stuff.

**Comment by joshhunt** [comment]
Sweet. I've pinned to the exact version of socket.io to try and reduce these issues.

If you get a chance, feel free to issue a PR to upgrade socket.io and stub out the correct thing.
